name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/maven-package.yml@d024bd332b95e4640e0838d69fddde6a7cfc549a
    permissions:
      contents: read
      packages: write
    with:
      java-version: '23'
      distribution: temurin
      # Set if you want the special root-POM deploy path:
      # deploy_root_artifact_id: 'crypto-trader'
    secrets: inherit
