name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/maven-package.yml@8b6c88b6b92ee4076f7b93b8412969aad2b1d93f
    permissions:
      contents: read
      packages: write
    with:
      java-version: '23'
      distribution: temurin
      # Set if you want the special root-POM deploy path:
      # deploy_root_artifact_id: 'crypto-trader'
    secrets: inherit
