name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/maven-package.yml@master
    with:
      java-version: '23'
      distribution: temurin
    secrets: inherit
