name: Reusable Maven Package & Deploy

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version"
        required: false
        default: '23'
        type: string
      distribution:
        description: "JDK distribution"
        required: false
        default: 'temurin'
        type: string
      deploy_root_artifact_id:
        description: "If set, deploy the aggregator/root POM when artifactId matches this value"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Build with Maven
        run: mvn -B -s "$GITHUB_WORKSPACE/settings.xml" package --file pom.xml

      - name: Deploy modules (skip if version exists)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          DEPLOY_ROOT_ARTIFACT: ${{ inputs.deploy_root_artifact_id }}
        run: |
          set -e
          echo "Discovering modules..."
          poms=$(git ls-files "pom.xml" ":(glob)**/pom.xml")
          echo "Found POMs:"
          echo "$poms"

          for pom in $poms; do
            PACK=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.packaging)
            G=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.groupId)
            A=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.artifactId)
            V=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.version)
            GP=${G//./\/}
            URL="https://maven.pkg.github.com/${REPO}/${GP}/${A}/${V}/${A}-${V}.pom"

            echo "Checking $A:$V at $URL"
            code=$(curl -L -s -o /dev/null -w "%{http_code}" -u "${{ github.actor }}:${GITHUB_TOKEN}" "$URL")
            if [ "$code" = "200" ]; then
              echo "Artifact already exists (HTTP 200). Skipping deploy for $A:$V"
              continue
            fi
            if [ "$code" = "401" ] || [ "$code" = "403" ]; then
              echo "Auth check issue for $A:$V (HTTP $code). Proceeding with deploy to avoid false skip."
            fi

            log="deploy_${A}_${V}.log"
            if [ "$PACK" = "pom" ]; then
              echo "Deploying POM $A:$V from $pom"
              set +e
              if [ -n "$DEPLOY_ROOT_ARTIFACT" ] && [ "$A" = "$DEPLOY_ROOT_ARTIFACT" ]; then
                mvn -B -N -f "$GITHUB_WORKSPACE/pom.xml" -DskipExisting=true deploy -s "$GITHUB_WORKSPACE/settings.xml" 2>&1 | tee "$log"
                rc=${PIPESTATUS[0]}
              else
                mvn -B -f "$GITHUB_WORKSPACE/pom.xml" -pl ":$A" -am -DskipTests=true -DskipRootDeploy=true install -s "$GITHUB_WORKSPACE/settings.xml" 2>&1 | tee "$log"
                rc=${PIPESTATUS[0]}
                if [ $rc -eq 0 ]; then
                  mvn -B -f "$GITHUB_WORKSPACE/pom.xml" -pl ":$A" -DskipExisting=true -DskipRootDeploy=true deploy -s "$GITHUB_WORKSPACE/settings.xml" 2>&1 | tee -a "$log"
                  rc=${PIPESTATUS[0]}
                fi
              fi
              set -e
              if [ $rc -ne 0 ]; then
                if grep -Ei -q "(status code: 409|Return code is: 409|409[^0-9]*Conflict)" "$log"; then
                  echo "Received 409 Conflict for $A:$V. Assuming already present. Skipping."
                  continue
                else
                  echo "Deploy failed for $A:$V with code $rc"
                  exit $rc
                fi
              fi
            else
              echo "Deploying $A:$V from $pom"
              set +e
              mvn -B -f "$GITHUB_WORKSPACE/pom.xml" -pl ":$A" -am -DskipTests=true -DskipRootDeploy=true install -s "$GITHUB_WORKSPACE/settings.xml" 2>&1 | tee "$log"
              rc=${PIPESTATUS[0]}
              if [ $rc -eq 0 ]; then
                mvn -B -f "$GITHUB_WORKSPACE/pom.xml" -pl ":$A" -DskipTests=true -DskipExisting=true -DskipRootDeploy=true deploy -s "$GITHUB_WORKSPACE/settings.xml" 2>&1 | tee -a "$log"
                rc=${PIPESTATUS[0]}
              fi
              set -e
              if [ $rc -ne 0 ]; then
                if grep -Ei -q "(status code: 409|Return code is: 409|409[^0-9]*Conflict)" "$log"; then
                  echo "Received 409 Conflict for $A:$V. Assuming already present. Skipping."
                  continue
                else
                  echo "Deploy failed for $A:$V with code $rc"
                  exit $rc
                fi
              fi
            fi
          done
