name: Post updates to X
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [ closed ]
    branches: [ "main", "master" ]
  issues:
    types: [ opened ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  promo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: Run Promo Bot
        uses: theoliverlear/Sigwarth-Software-Suite@v0.1.1
        with:
          app_name: "Sigwarth Software Suite"
          mode: prod
        env:
          OPENAI_KEY:      ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN:    ${{ secrets.GH_TOKEN }}
          X_API_KEY:       ${{ secrets.X_API_KEY }}
          X_SECRET:        ${{ secrets.X_SECRET }}
          X_ACCESS_TOKEN:  ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          APP_NAME:        ${{ secrets.APP_NAME }}
          REPO_NAME:       ${{ secrets.REPO_NAME }}
