name: Post updates to X
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [ closed ]
    branches: [ "main", "master" ]
  issues:
    types: [ opened ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  promo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: Run Promo Bot
        uses: theoliverlear/Sigwarth-Software-Suite/.github/actions/promo@master
        with:
          app_name: "Sigwarth Software Suite"
          mode: prod
          openai_key:      ${{ secrets.OPENAI_KEY }}
          github_token:    ${{ secrets.GITHUB_TOKEN }}
          x_api_key:       ${{ secrets.X_API_KEY }}
          x_secret:        ${{ secrets.X_SECRET }}
          x_access_token:  ${{ secrets.X_ACCESS_TOKEN }}
          x_access_secret: ${{ secrets.X_ACCESS_SECRET }}
          repo_name:       ${{ secrets.REPO_NAME }}
