# .github/workflows/release-publish.yml
name: Release
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
  packages: write

jobs:
  publish-all:
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/release-package.yml@51d72a1c313325a3c155896202110792e5a68306
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      package_matrix: |
        [
          {"package_name":"@theoliverlear/styles-suite","package_dir":"Npm-Suite/styles-suite","verify_files":"package.json index.scss"},
          {"package_name":"@theoliverlear/angular-suite","package_dir":"Npm-Suite/angular-suite","build_command":"npm run build","dist_dir":"dist"}
        ]
