name: Release Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to publish (styles-suite, angular-suite, all)"
        required: false
        default: 'all'
  release:
    types: [published]

jobs:
  publish-styles-suite:
    if: ${{ github.event_name == 'release' || github.event.inputs.package == 'all' || github.event.inputs.package == 'styles-suite' || github.event.inputs.package == '' }}
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/release-package.yml@master
    permissions:
      contents: read
      packages: write
    with:
      package_name: '@theoliverlear/styles-suite'
      package_dir: 'Npm-Suite/styles-suite'
      scss_package: true
      node_version: '20'
    secrets: inherit

  publish-angular-suite:
    if: ${{ github.event_name == 'release' || github.event.inputs.package == 'all' || github.event.inputs.package == 'angular-suite' }}
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/release-package.yml@master
    permissions:
      contents: read
      packages: write
    with:
      package_name: '@theoliverlear/angular-suite'
      package_dir: 'Npm-Suite/angular-suite'
      scss_package: false
      build_script: 'npm run build'
      dist_dir: 'dist'
      node_version: '20'
    secrets: inherit
